AWSTemplateFormatVersion: '2010-09-09'
Description: code-deploy-cfntest
Resources:
  PythonLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: lambda function test
      FunctionName: LambdaPython
      Handler: lambda_handler
      Code: ../
      MemorySize: 256
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6
      Timeout: 10

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
